<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Option;
use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $historyCategory = Category::where('name', 'Histoire & Politique')->first()?->id;
        $geographyCategory = Category::where('name', 'Géographie')->first()?->id;
        $gastronomyCategory = Category::where('name', 'Gastronomie & Traditions')->first()?->id;

        if (! $historyCategory || ! $geographyCategory || ! $gastronomyCategory) {
            $this->command?->error('Les catégories requises sont manquantes. Exécutez CategorySeeder avant QuestionSeeder.');
            return;
        }

        $questionsByCategory = [
            $historyCategory => [
                ['type'=>'qcm','difficulty'=>1,'question_text'=>"En quelle année la Côte d'Ivoire a-t-elle proclamé son indépendance ?",'explanation'=>"La Côte d'Ivoire a proclamé son indépendance le 7 août 1960, se séparant pacifiquement de la France. Le 7 août est aujourd'hui célébré comme la fête nationale ivoirienne.",'options'=>[['text'=>'1958','correct'=>false],['text'=>'1960','correct'=>true],['text'=>'1962','correct'=>false],['text'=>'1965','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>"Qui a été le premier président de la Côte d'Ivoire ?",'explanation'=>"Félix Houphouët-Boigny fut le premier et le plus long président de Côte d'Ivoire, gouvernant de 1960 jusqu'à sa mort en 1993. Il est considéré comme le père de la nation ivoirienne.",'options'=>[['text'=>'Laurent Gbagbo','correct'=>false],['text'=>'Henri Konan Bédié','correct'=>false],['text'=>'Félix Houphouët-Boigny','correct'=>true],['text'=>'Alassane Ouattara','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle est la capitale politique de la Côte d'Ivoire ?",'explanation'=>"Yamoussoukro est la capitale politique et administrative officielle depuis 1983. Abidjan reste cependant la capitale économique et la plus grande ville du pays.",'options'=>[['text'=>'Abidjan','correct'=>false],['text'=>'Bouaké','correct'=>false],['text'=>'Yamoussoukro','correct'=>true],['text'=>'San-Pédro','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel est le symbole animal officiel de la Côte d'Ivoire ?",'explanation'=>"L'éléphant est le symbole national de la Côte d'Ivoire. Il représente la force, la sagesse et la longévité. Les joueurs ivoiriens de football sont d'ailleurs surnommés les Éléphants.",'options'=>[['text'=>'Le lion','correct'=>false],['text'=>"L'éléphant",'correct'=>true],['text'=>'La panthère','correct'=>false],['text'=>'Le buffle','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>"Dans quelle ville se trouve la Basilique Notre-Dame de la Paix, l'une des plus grandes églises du monde ?",'explanation'=>"La Basilique Notre-Dame de la Paix de Yamoussoukro, construite par Houphouët-Boigny, est inscrite au Guinness des records comme la plus grande église du monde en termes de superficie.",'options'=>[['text'=>'Abidjan','correct'=>false],['text'=>'Bouaké','correct'=>false],['text'=>'Daloa','correct'=>false],['text'=>'Yamoussoukro','correct'=>true]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel accord a mis fin à la crise politico-militaire ivoirienne de 2002-2007 ?",'explanation'=>"L'Accord politique de Ouagadougou (APO) signé le 4 mars 2007 au Burkina Faso a permis de sortir la Côte d'Ivoire de la crise déclenchée en septembre 2002.",'options'=>[['text'=>'Accord de Marcoussis','correct'=>false],['text'=>'Accord de Ouagadougou','correct'=>true],['text'=>'Accord de Pretoria','correct'=>false],['text'=>'Accord de Linas-Marcoussis','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>"De quelle couleur est la bande gauche du drapeau ivoirien ?",'explanation'=>"Le drapeau de Côte d'Ivoire est composé de trois bandes verticales : orange à gauche, blanc au centre et vert à droite. L'orange symbolise la savane du nord, le blanc la paix et le vert les forêts du sud.",'options'=>[['text'=>'Vert','correct'=>false],['text'=>'Blanc','correct'=>false],['text'=>'Orange','correct'=>true],['text'=>'Rouge','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"Félix Houphouët-Boigny a gouverné la Côte d'Ivoire pendant plus de 30 ans.",'explanation'=>"Vrai. Félix Houphouët-Boigny a été président de 1960 à 1993, soit 33 ans de gouvernance, ce qui en fait l'un des dirigeants africains les plus longevistes.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Abidjan est la capitale officielle de la Côte d'Ivoire.",'explanation'=>"Faux. Bien qu'Abidjan soit la plus grande ville et la capitale économique, la capitale officielle est Yamoussoukro depuis le décret présidentiel de 1983.",'options'=>[['text'=>'Vrai','correct'=>false],['text'=>'Faux','correct'=>true]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quel fleuve traverse Yamoussoukro ?','explanation'=>'Le fleuve Bandama traverse la région de Yamoussoukro. C\'est le plus long fleuve entièrement ivoirien avec ses 1050 km de longueur.','options'=>[['text'=>'Le Bandama','correct'=>true],['text'=>'Le Sassandra','correct'=>false],['text'=>'La Comoé','correct'=>false],['text'=>'Le Cavally','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>"En quelle année la Côte d'Ivoire a-t-elle organisé sa première Coupe d'Afrique des Nations de football ?",'explanation'=>"La Côte d'Ivoire a accueilli la CAN 1984 qu'elle a remportée en battant le Nigeria en finale. Ce fut leur premier titre continental.",'options'=>[['text'=>'1984','correct'=>true],['text'=>'1992','correct'=>false],['text'=>'1996','correct'=>false],['text'=>'2000','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"La Côte d'Ivoire est le premier producteur mondial de cacao.",'explanation'=>"Vrai. La Côte d'Ivoire est le premier producteur et exportateur mondial de cacao depuis des décennies, représentant environ 40% de la production mondiale.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Comment surnomme-t-on Abidjan sur le plan international ?','explanation'=>'Abidjan est souvent surnommée le Paris de l\'Afrique de l\'Ouest en raison de son architecture moderne, ses quartiers d\'affaires et son dynamisme économique.','options'=>[['text'=>'La perle de l\'Afrique','correct'=>false],['text'=>'Paris de l\'Afrique de l\'Ouest','correct'=>true],['text'=>'La capitale africaine','correct'=>false],['text'=>'La ville lumière africaine','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>2,'question_text'=>'Le nouchi est une langue officielle de Côte d\'Ivoire.','explanation'=>'Faux. Le nouchi est un argot populaire ivoirien mêlant français et plusieurs langues locales. La seule langue officielle de Côte d\'Ivoire est le français.','options'=>[['text'=>'Vrai','correct'=>false],['text'=>'Faux','correct'=>true]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>'Quel est le nom du parlement de la Côte d\'Ivoire ?','explanation'=>'La Côte d\'Ivoire dispose d\'un parlement bicaméral composé de l\'Assemblée Nationale et du Sénat depuis la constitution de 2016.','options'=>[['text'=>'Le Sénat National','correct'=>false],['text'=>'L\'Assemblée Fédérale','correct'=>false],['text'=>'L\'Assemblée Nationale','correct'=>true],['text'=>'Le Congrès Ivoirien','correct'=>false]]],
            ],
            $geographyCategory => [
                ['type'=>'qcm','difficulty'=>1,'question_text'=>"Avec combien de pays la Côte d'Ivoire partage-t-elle ses frontières ?",'explanation'=>"La Côte d'Ivoire partage ses frontières avec 5 pays : le Ghana à l'est, le Burkina Faso et le Mali au nord, la Guinée et le Liberia à l'ouest.",'options'=>[['text'=>'3 pays','correct'=>false],['text'=>'4 pays','correct'=>false],['text'=>'5 pays','correct'=>true],['text'=>'6 pays','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'Quelle est la deuxième plus grande ville de Côte d\'Ivoire ?','explanation'=>'Bouaké est la deuxième plus grande ville de Côte d\'Ivoire après Abidjan. Située au centre du pays, elle est un important carrefour commercial et économique.','options'=>[['text'=>'Yamoussoukro','correct'=>false],['text'=>'San-Pédro','correct'=>false],['text'=>'Bouaké','correct'=>true],['text'=>'Daloa','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quel est le plus grand port de Côte d\'Ivoire ?','explanation'=>'Le Port Autonome d\'Abidjan est le plus grand port de Côte d\'Ivoire et l\'un des plus importants d\'Afrique de l\'Ouest, traitant plus de 20 millions de tonnes de marchandises par an.','options'=>[['text'=>'Port de Sassandra','correct'=>false],['text'=>'Port d\'Abidjan','correct'=>true],['text'=>'Port de San-Pédro','correct'=>false],['text'=>'Port de Grand-Bassam','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>1,'question_text'=>'La Côte d\'Ivoire est un pays enclavé sans accès à la mer.','explanation'=>'Faux. La Côte d\'Ivoire possède une façade maritime d\'environ 550 km sur l\'océan Atlantique (golfe de Guinée) au sud du pays.','options'=>[['text'=>'Vrai','correct'=>false],['text'=>'Faux','correct'=>true]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quel est le point culminant de la Côte d\'Ivoire ?','explanation'=>'Le Mont Nimba culmine à 1752 mètres d\'altitude à la frontière entre la Côte d\'Ivoire, la Guinée et le Liberia. Il est classé réserve de biosphère par l\'UNESCO.','options'=>[['text'=>'Mont Nimba','correct'=>true],['text'=>'Mont Tonkoui','correct'=>false],['text'=>'Mont Péko','correct'=>false],['text'=>'Mont Sangbé','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'Dans quel quartier d\'Abidjan se trouve le célèbre marché de Cocody ?','explanation'=>'Le marché de Cocody se trouve dans la commune de Cocody, l\'un des quartiers résidentiels et diplomatiques les plus huppés d\'Abidjan.','options'=>[['text'=>'Plateau','correct'=>false],['text'=>'Marcory','correct'=>false],['text'=>'Cocody','correct'=>true],['text'=>'Yopougon','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quelle lagune longe le quartier du Plateau à Abidjan ?','explanation'=>'La lagune Ébrié est la plus grande lagune de Côte d\'Ivoire avec 566 km². Elle traverse Abidjan et sépare plusieurs communes de la ville.','options'=>[['text'=>'Lagune Aby','correct'=>false],['text'=>'Lagune Ébrié','correct'=>true],['text'=>'Lagune Tendo','correct'=>false],['text'=>'Lagune Aghien','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>2,'question_text'=>'Le Parc National de Taï est classé au patrimoine mondial de l\'UNESCO.','explanation'=>'Vrai. Le Parc National de Taï, situé dans le sud-ouest du pays, est classé au patrimoine mondial de l\'UNESCO depuis 1982. C\'est l\'une des dernières grandes forêts tropicales primaires d\'Afrique de l\'Ouest.','options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>'Quelle ville ivoirienne est connue comme la capitale du café ?','explanation'=>'Gagnoa dans la région du Gôh est réputée pour sa production de café et de cacao. La région Centre-Ouest est l\'une des plus productives du pays en termes de cultures d\'exportation.','options'=>[['text'=>'Daloa','correct'=>false],['text'=>'Man','correct'=>false],['text'=>'Divo','correct'=>false],['text'=>'Gagnoa','correct'=>true]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Combien de régions administratives compte la Côte d\'Ivoire ?','explanation'=>'La Côte d\'Ivoire est divisée en 14 districts autonomes et 31 régions administratives selon le découpage territorial actuel.','options'=>[['text'=>'19 régions','correct'=>false],['text'=>'31 régions','correct'=>true],['text'=>'25 régions','correct'=>false],['text'=>'14 régions','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>1,'question_text'=>'San-Pédro est le deuxième port en importance de Côte d\'Ivoire.','explanation'=>'Vrai. Le port de San-Pédro est le deuxième port ivoirien et le premier port mondial d\'exportation de cacao en fèves, traitant une grande partie de la production nationale.','options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>'Quel fleuve forme une partie de la frontière entre la Côte d\'Ivoire et le Liberia ?','explanation'=>'Le fleuve Cavally forme la frontière naturelle entre la Côte d\'Ivoire et le Liberia sur environ 320 km. Il se jette dans l\'océan Atlantique près de la ville de Tabou.','options'=>[['text'=>'Le Bandama','correct'=>false],['text'=>'La Comoé','correct'=>false],['text'=>'Le Cavally','correct'=>true],['text'=>'Le Sassandra','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quelle est la commune la plus peuplée d\'Abidjan ?','explanation'=>'Yopougon est la commune la plus peuplée d\'Abidjan avec plus de 2 millions d\'habitants. Elle est souvent appelée Yop City et est connue pour son ambiance populaire et sa vie nocturne.','options'=>[['text'=>'Cocody','correct'=>false],['text'=>'Plateau','correct'=>false],['text'=>'Yopougon','correct'=>true],['text'=>'Abobo','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>2,'question_text'=>'La Côte d\'Ivoire possède une frontière maritime avec le Ghana.','explanation'=>'Faux. La Côte d\'Ivoire et le Ghana partagent uniquement une frontière terrestre à l\'est du pays. Les deux pays ont cependant une Zone Économique Exclusive maritime adjacente.','options'=>[['text'=>'Vrai','correct'=>false],['text'=>'Faux','correct'=>true]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'Quelle ville ivoirienne est surnommée la ville aux collines ?','explanation'=>'Man est surnommée la ville aux collines en raison de son relief montagneux dans la région du Tonkpi à l\'ouest du pays. Elle est connue pour ses danses traditionnelles sur échasses.','options'=>[['text'=>'Bouaké','correct'=>false],['text'=>'Daloa','correct'=>false],['text'=>'Man','correct'=>true],['text'=>'Odienné','correct'=>false]]],
            ],
            $gastronomyCategory => [
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'Quel est le plat national le plus emblématique de la Côte d\'Ivoire ?','explanation'=>'L\'attiéké poisson est le plat le plus emblématique de Côte d\'Ivoire. L\'attiéké est une semoule de manioc fermenté, généralement servie avec du poisson grillé et de la sauce tomate. C\'est le plat du quotidien ivoirien.','options'=>[['text'=>'Le thiéboudienne','correct'=>false],['text'=>'Le foutou bangui','correct'=>false],['text'=>"L'attiéké poisson",'correct'=>true],['text'=>'Le kedjenou','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'De quoi est fait l\'attiéké ?','explanation'=>'L\'attiéké est préparé à partir de manioc fermenté et râpé. C\'est une spécialité des peuples Adjoukrou et Avikam de la région de Jacqueville et Grand-Lahou.','options'=>[['text'=>'De mil','correct'=>false],['text'=>'De manioc fermenté','correct'=>true],['text'=>'De maïs','correct'=>false],['text'=>'De riz','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Qu\'est-ce que le kedjenou ?','explanation'=>'Le kedjenou est un plat traditionnel ivoirien préparé en faisant mijoter de la volaille ou de la viande avec des légumes dans un canari (poterie en terre cuite) hermétiquement fermé. C\'est une spécialité Baoulé.','options'=>[['text'=>'Un dessert ivoirien','correct'=>false],['text'=>'Une boisson traditionnelle','correct'=>false],['text'=>'Un ragoût mijoté en canari','correct'=>true],['text'=>'Une sauce pimentée','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>1,'question_text'=>'Le garba est un plat populaire à base d\'attiéké et de thon.','explanation'=>'Vrai. Le garba est un plat populaire et économique composé d\'attiéké et de thon frit, souvent accompagné d\'oignons et de piment. Il est particulièrement apprécié par les étudiants et travailleurs d\'Abidjan.','options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quelle boisson traditionnelle ivoirienne est fabriquée à partir de palme ?','explanation'=>'Le bangui est le vin de palme traditionnel ivoirien, extrait du palmier à huile. C\'est une boisson fermentée très appréciée dans les villages et lors des cérémonies traditionnelles.','options'=>[['text'=>'Le bangui','correct'=>true],['text'=>'Le tchapalo','correct'=>false],['text'=>'Le bisap','correct'=>false],['text'=>'Le gnamakoudji','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'Quel peuple ivoirien est réputé pour la danse des masques ?','explanation'=>'Les Dan, aussi appelés Yacouba, originaires de l\'ouest de la Côte d\'Ivoire (région de Man), sont célèbres pour leur danse sur échasses et leurs masques traditionnels reconnus dans le monde entier.','options'=>[['text'=>'Les Baoulé','correct'=>false],['text'=>'Les Dioula','correct'=>false],['text'=>'Les Dan (Yacouba)','correct'=>true],['text'=>'Les Agni','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Qu\'est-ce que le foutou ?','explanation'=>'Le foutou est un plat traditionnel à base de banane plantain ou d\'igname pilée jusqu\'à obtenir une pâte lisse et élastique. Il est généralement servi avec de la sauce graine, de la sauce arachide ou de la sauce claire.','options'=>[['text'=>'Une sauce épicée','correct'=>false],['text'=>'Un plat de pâte pilée','correct'=>true],['text'=>'Un dessert sucré','correct'=>false],['text'=>'Une boisson fermentée','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>2,'question_text'=>'Le coupé-décalé est un style musical né en Côte d\'Ivoire.','explanation'=>'Vrai. Le coupé-décalé est un genre musical et une danse né à Paris dans la communauté ivoirienne au début des années 2000, popularisé par Douk Saga. Il est aujourd\'hui l\'un des genres musicaux les plus influents d\'Afrique de l\'Ouest.','options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quel tissu traditionnel est associé aux cérémonies royales ivoiriennes ?','explanation'=>'Le kente est un tissu tissé aux couleurs vives, originaire des peuples Akan (Baoulé, Agni) de Côte d\'Ivoire et du Ghana. Il est porté lors des cérémonies importantes et symbolise la royauté.','options'=>[['text'=>'Le bogolan','correct'=>false],['text'=>'Le kente','correct'=>true],['text'=>'Le bazin','correct'=>false],['text'=>'Le wax','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>'Quel est le nom de la fête traditionnelle Baoulé qui marque les premières récoltes ?','explanation'=>'L\'Adjanou est la fête traditionnelle Baoulé qui célèbre les premières récoltes et rend hommage aux ancêtres. C\'est un moment de communion entre les vivants et les esprits des ancêtres.','options'=>[['text'=>"L'Abissa",'correct'=>false],['text'=>'Le Dipri','correct'=>false],['text'=>"L'Adjanou",'correct'=>true],['text'=>'Le Festima','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>1,'question_text'=>'Le placali est un plat à base de manioc.','explanation'=>'Vrai. Le placali est une pâte à base de manioc, de consistance gélatineuse, très consommée dans le sud et le centre de la Côte d\'Ivoire. Il est souvent servi avec de la sauce graine ou de la soupe de poisson.','options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>2,'question_text'=>'Quelle fête populaire des peuples Adjoukrou est célébrée à Jacqueville ?','explanation'=>'Le Dipri est une fête rituelle du peuple Adjoukrou célébrée à Gomon près de Jacqueville. Cette nuit sacrée implique des rites de purification et de communication avec les ancêtres.','options'=>[['text'=>"L'Abissa",'correct'=>false],['text'=>'Le Dipri','correct'=>true],['text'=>"L'Adjanou",'correct'=>false],['text'=>'Le Popo Carneval','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>1,'question_text'=>'Comment appelle-t-on le petit restaurant populaire de rue en Côte d\'Ivoire ?','explanation'=>'Le maquis est le nom donné aux petits restaurants populaires ivoiriens, souvent en plein air, où l\'on sert des plats locaux à prix abordables. C\'est un lieu de vie sociale incontournable en Côte d\'Ivoire.','options'=>[['text'=>'Le maquis','correct'=>true],['text'=>'Le grin','correct'=>false],['text'=>'Le cabaret','correct'=>false],['text'=>'Le garba','correct'=>false]]],
                ['type'=>'vrai_faux','difficulty'=>2,'question_text'=>'Le zouglou est un genre musical ivoirien né dans les universités.','explanation'=>'Vrai. Le zouglou est né dans les cités universitaires d\'Abidjan dans les années 1990. C\'est un genre musical engagé qui mêle complaintes sociales, humour et critique politique. Il est souvent accompagné de la danse du même nom.','options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
                ['type'=>'qcm','difficulty'=>3,'question_text'=>'Quel est l\'instrument de musique traditionnel emblématique des peuples du nord de la Côte d\'Ivoire ?','explanation'=>'La kora est un instrument à cordes emblématique des griots d\'Afrique de l\'Ouest, très présent dans le nord de la Côte d\'Ivoire notamment chez les peuples Mandé et Dioula. Elle possède 21 cordes et produit un son mélodieux.','options'=>[['text'=>'Le djembé','correct'=>false],['text'=>'La kora','correct'=>true],['text'=>'Le balafon','correct'=>false],['text'=>'Le tam-tam','correct'=>false]]],
            ],
        ];

        foreach ($questionsByCategory as $categoryId => $questions) {
            foreach ($questions as $questionData) {
                $question = Question::updateOrCreate(
                    [
                        'category_id' => $categoryId,
                        'question_text' => $questionData['question_text'],
                    ],
                    [
                        'type' => $questionData['type'],
                        'explanation' => $questionData['explanation'],
                        'difficulty' => $questionData['difficulty'],
                        'is_active' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );

                foreach ($questionData['options'] as $optionData) {
                    Option::updateOrCreate(
                        [
                            'question_id' => $question->id,
                            'option_text' => $optionData['text'],
                        ],
                        [
                            'is_correct' => $optionData['correct'],
                            'created_at' => now(),
                            'updated_at' => now(),
                        ]
                    );
                }
            }
        }
    }
}
