<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Option;
use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Récupération de toutes les catégories
        $categories = [
            'Histoire & Politique' => Category::where('name', 'Histoire & Politique')->first()?->id,
            'Géographie' => Category::where('name', 'Géographie')->first()?->id,
            'Gastronomie & Traditions' => Category::where('name', 'Gastronomie & Traditions')->first()?->id,
            'Culture & Arts' => Category::where('name', 'Culture & Arts')->first()?->id,
            'Sport ivoirien' => Category::where('name', 'Sport ivoirien')->first()?->id,
            'Économie & Développement' => Category::where('name', 'Économie & Développement')->first()?->id,
            'Langues & Peuples' => Category::where('name', 'Langues & Peuples')->first()?->id,
            'Personnalités ivoiriennes' => Category::where('name', 'Personnalités ivoiriennes')->first()?->id,
            'Musique ivoirienne' => Category::where('name', 'Musique ivoirienne')->first()?->id,
            'Villes & Régions' => Category::where('name', 'Villes & Régions')->first()?->id,
            'Patrimoine & Tourisme' => Category::where('name', 'Patrimoine & Tourisme')->first()?->id,
            'Éducation & Société' => Category::where('name', 'Éducation & Société')->first()?->id,
            'Christianisme en Côte d’Ivoire' => Category::where('name', 'Christianisme en Côte d’Ivoire')->first()?->id,
            'Foursquare en Côte d’Ivoire' => Category::where('name', 'Foursquare en Côte d’Ivoire')->first()?->id,
        ];

        // Vérification que toutes les catégories existent
        foreach ($categories as $name => $id) {
            if (! $id) {
                $this->command?->error("La catégorie '$name' est manquante. Exécutez CategorySeeder avant QuestionSeeder.");
                return;
            }
        }

        $questionsByCategory = [
            // ==================== HISTOIRE & POLITIQUE (15 questions) ====================
            $categories['Histoire & Politique'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"En quelle année la Côte d'Ivoire a-t-elle proclamé son indépendance ?",'explanation'=>"La Côte d'Ivoire a proclamé son indépendance le 7 août 1960.",'options'=>[['text'=>'1958','correct'=>false],['text'=>'1960','correct'=>true],['text'=>'1962','correct'=>false],['text'=>'1965','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Qui a été le premier président de la Côte d'Ivoire ?",'explanation'=>"Félix Houphouët-Boigny a été le premier président du pays.",'options'=>[['text'=>'Félix Houphouët-Boigny','correct'=>true],['text'=>'Henri Konan Bédié','correct'=>false],['text'=>'Laurent Gbagbo','correct'=>false],['text'=>'Alassane Ouattara','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"Le 7 août est la fête nationale ivoirienne.",'explanation'=>"Le 7 août rappelle l’indépendance de la Côte d’Ivoire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville est la capitale politique de la Côte d'Ivoire ?",'explanation'=>"Yamoussoukro est la capitale politique et administrative du pays.",'options'=>[['text'=>'Abidjan','correct'=>false],['text'=>'Bouaké','correct'=>false],['text'=>'Yamoussoukro','correct'=>true],['text'=>'San Pedro','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel symbole national contient trois bandes verticales orange, blanche et verte ?",'explanation'=>"Le drapeau ivoirien est composé de trois bandes verticales orange, blanche et verte.",'options'=>[['text'=>'Le drapeau','correct'=>true],['text'=>'Les armoiries','correct'=>false],['text'=>'La devise','correct'=>false],['text'=>'L’hymne','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle est la devise de la Côte d'Ivoire ?",'explanation'=>"La devise nationale est Union, Discipline, Travail.",'options'=>[['text'=>'Unité, Paix, Progrès','correct'=>false],['text'=>'Union, Discipline, Travail','correct'=>true],['text'=>'Liberté, Égalité, Fraternité','correct'=>false],['text'=>'Justice, Paix, Solidarité','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel hymne national ivoirien est chanté lors des cérémonies officielles ?",'explanation'=>"L’Abidjanaise est l’hymne national de la Côte d’Ivoire.",'options'=>[['text'=>'L’Abidjanaise','correct'=>true],['text'=>'La Marseillaise','correct'=>false],['text'=>'Le Chant du départ','correct'=>false],['text'=>'La Concorde','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Abidjan a longtemps été la capitale administrative avant Yamoussoukro.",'explanation'=>"Abidjan a joué un rôle central avant le transfert officiel de la capitale à Yamoussoukro.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"En quelle année Yamoussoukro est-elle devenue capitale politique de la Côte d'Ivoire ?",'explanation'=>"Yamoussoukro est devenue capitale politique en 1983.",'options'=>[['text'=>'1960','correct'=>false],['text'=>'1975','correct'=>false],['text'=>'1983','correct'=>true],['text'=>'1993','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel pays a colonisé la Côte d'Ivoire avant son indépendance ?",'explanation'=>"La Côte d’Ivoire était une colonie française avant 1960.",'options'=>[['text'=>'La France','correct'=>true],['text'=>'Le Portugal','correct'=>false],['text'=>'L’Espagne','correct'=>false],['text'=>'L’Allemagne','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"La Côte d'Ivoire est membre de l'Union africaine.",'explanation'=>"La Côte d’Ivoire participe aux institutions de l’Union africaine.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel organe représente la chambre basse du Parlement ivoirien depuis la Constitution de 2016 ?",'explanation'=>"L’Assemblée nationale est la chambre basse du Parlement ivoirien.",'options'=>[['text'=>'Le Sénat','correct'=>false],['text'=>'L’Assemblée nationale','correct'=>true],['text'=>'La Cour suprême','correct'=>false],['text'=>'Le Conseil économique','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quelle institution forme avec l’Assemblée nationale le Parlement ivoirien bicaméral ?",'explanation'=>"Le Parlement ivoirien comprend l’Assemblée nationale et le Sénat.",'options'=>[['text'=>'Le Sénat','correct'=>true],['text'=>'La Cour des comptes','correct'=>false],['text'=>'Le Conseil constitutionnel','correct'=>false],['text'=>'La Primature','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel ancien nom désignait la Côte d'Ivoire sous l’administration coloniale française ?",'explanation'=>"La Côte d’Ivoire était une colonie de l’Afrique occidentale française.",'options'=>[['text'=>'Afrique occidentale française','correct'=>true],['text'=>'Afrique équatoriale belge','correct'=>false],['text'=>'Gold Coast','correct'=>false],['text'=>'Dahomey oriental','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"La Côte d'Ivoire a adopté une Constitution instituant un Sénat en 2016.",'explanation'=>"La Constitution de 2016 a instauré un Parlement bicaméral avec un Sénat.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Géographie'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Sur quel continent se trouve la Côte d'Ivoire ?",'explanation'=>"La Côte d’Ivoire est située en Afrique de l’Ouest.",'options'=>[['text'=>'Afrique','correct'=>true],['text'=>'Europe','correct'=>false],['text'=>'Asie','correct'=>false],['text'=>'Amérique','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel océan borde le sud de la Côte d'Ivoire ?",'explanation'=>"Le sud du pays est bordé par l’océan Atlantique.",'options'=>[['text'=>'Océan Indien','correct'=>false],['text'=>'Océan Atlantique','correct'=>true],['text'=>'Océan Pacifique','correct'=>false],['text'=>'Océan Arctique','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville ivoirienne est un grand port sur l’Atlantique ?",'explanation'=>"Abidjan possède un important port maritime.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'Man','correct'=>false],['text'=>'Bondoukou','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"La Côte d'Ivoire est un pays d'Afrique de l'Ouest.",'explanation'=>"Elle se situe sur la façade atlantique de l’Afrique de l’Ouest.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel pays est à l’est de la Côte d'Ivoire ?",'explanation'=>"Le Ghana se trouve à l’est de la Côte d’Ivoire.",'options'=>[['text'=>'Ghana','correct'=>true],['text'=>'Sénégal','correct'=>false],['text'=>'Tchad','correct'=>false],['text'=>'Cameroun','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel fleuve important traverse la Côte d'Ivoire du nord au sud ?",'explanation'=>"Le Bandama est l’un des principaux fleuves ivoiriens.",'options'=>[['text'=>'Bandama','correct'=>true],['text'=>'Nil','correct'=>false],['text'=>'Congo','correct'=>false],['text'=>'Sénégal','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle zone naturelle domine le nord de la Côte d'Ivoire ?",'explanation'=>"Le nord du pays est marqué par des savanes.",'options'=>[['text'=>'Savanes','correct'=>true],['text'=>'Désert chaud','correct'=>false],['text'=>'Toundra','correct'=>false],['text'=>'Banquise','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville est située dans l’ouest montagneux de la Côte d'Ivoire ?",'explanation'=>"Man est connue pour son relief montagneux et ses paysages verdoyants.",'options'=>[['text'=>'Man','correct'=>true],['text'=>'Grand-Bassam','correct'=>false],['text'=>'Dabou','correct'=>false],['text'=>'Aboisso','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"La Côte d'Ivoire partage une frontière avec le Burkina Faso.",'explanation'=>"Le Burkina Faso est un voisin au nord de la Côte d’Ivoire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel parc national ivoirien se situe dans l’ouest du pays ?",'explanation'=>"Le parc national de Taï est situé dans l’ouest ivoirien.",'options'=>[['text'=>'Parc national de Taï','correct'=>true],['text'=>'Parc de la Comoé','correct'=>false],['text'=>'Parc du W','correct'=>false],['text'=>'Parc de Zakouma','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel fleuve donne son nom à un grand parc national du nord-est ivoirien ?",'explanation'=>"Le parc national de la Comoé porte le nom du fleuve Comoé.",'options'=>[['text'=>'Comoé','correct'=>true],['text'=>'Sassandra','correct'=>false],['text'=>'Cavally','correct'=>false],['text'=>'Niger','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le mont Nimba se trouve à la frontière ouest de la Côte d'Ivoire.",'explanation'=>"Le massif du Nimba est partagé entre la Côte d’Ivoire, la Guinée et le Liberia.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel fleuve forme une partie de la frontière entre la Côte d'Ivoire et le Liberia ?",'explanation'=>"Le Cavally marque une partie de la frontière ouest du pays.",'options'=>[['text'=>'Cavally','correct'=>true],['text'=>'Bandama','correct'=>false],['text'=>'Comoé','correct'=>false],['text'=>'Volta','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel est le point culminant généralement cité de la Côte d'Ivoire ?",'explanation'=>"Le mont Nimba est le plus haut sommet associé au territoire ivoirien.",'options'=>[['text'=>'Mont Nimba','correct'=>true],['text'=>'Mont Korhogo','correct'=>false],['text'=>'Mont Péko','correct'=>false],['text'=>'Mont Tonkoui','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Le parc national de la Comoé est l’un des plus vastes espaces protégés de Côte d'Ivoire.",'explanation'=>"Ce parc est reconnu pour son étendue et sa biodiversité.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Gastronomie & Traditions'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel plat ivoirien est préparé avec de la banane plantain pilée ?",'explanation'=>"Le foutou banane est fait à base de banane plantain pilée.",'options'=>[['text'=>'Foutou banane','correct'=>true],['text'=>'Attiéké','correct'=>false],['text'=>'Garba','correct'=>false],['text'=>'Kédjénou','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel aliment accompagne souvent le poisson thon dans le garba ?",'explanation'=>"Le garba associe généralement attiéké et thon frit.",'options'=>[['text'=>'Attiéké','correct'=>true],['text'=>'Riz au lait','correct'=>false],['text'=>'Couscous de blé','correct'=>false],['text'=>'Pain sucré','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"L’attiéké est fabriqué à partir de manioc.",'explanation'=>"L’attiéké est une semoule de manioc très consommée en Côte d’Ivoire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel plat ivoirien est souvent cuit à l’étouffée dans une marmite ?",'explanation'=>"Le kédjénou est un plat mijoté à l’étouffée.",'options'=>[['text'=>'Kédjénou','correct'=>true],['text'=>'Salade niçoise','correct'=>false],['text'=>'Pizza','correct'=>false],['text'=>'Couscous royal','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle boisson traditionnelle peut être tirée du palmier ?",'explanation'=>"Le vin de palme est une boisson traditionnelle issue du palmier.",'options'=>[['text'=>'Vin de palme','correct'=>true],['text'=>'Jus de pomme','correct'=>false],['text'=>'Thé vert','correct'=>false],['text'=>'Limonade','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel peuple est particulièrement associé à l’attiéké dans le sud ivoirien ?",'explanation'=>"L’attiéké est fortement associé aux peuples lagunaires comme les Ébrié.",'options'=>[['text'=>'Ébrié','correct'=>true],['text'=>'Sénoufo','correct'=>false],['text'=>'Lobi','correct'=>false],['text'=>'Malinké','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle sauce ivoirienne est préparée avec des graines de palmier ?",'explanation'=>"La sauce graine est faite à partir de noix de palme.",'options'=>[['text'=>'Sauce graine','correct'=>true],['text'=>'Sauce tomate simple','correct'=>false],['text'=>'Sauce blanche','correct'=>false],['text'=>'Sauce béchamel','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le foutou peut être accompagné de sauce graine.",'explanation'=>"Le foutou est souvent servi avec des sauces comme la sauce graine.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel plat populaire associe souvent attiéké, poisson, oignon et piment ?",'explanation'=>"Le garba est un repas populaire dans de nombreuses villes ivoiriennes.",'options'=>[['text'=>'Garba','correct'=>true],['text'=>'Alloco','correct'=>false],['text'=>'Placali','correct'=>false],['text'=>'Foutou igname','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel mets ivoirien est fait de bananes plantains frites ?",'explanation'=>"L’alloco est préparé avec des morceaux de banane plantain frits.",'options'=>[['text'=>'Alloco','correct'=>true],['text'=>'Placali','correct'=>false],['text'=>'Attoukpou','correct'=>false],['text'=>'Akpessi','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel tubercule est souvent utilisé pour préparer le foutou igname ?",'explanation'=>"Le foutou igname est préparé avec de l’igname pilée.",'options'=>[['text'=>'Igname','correct'=>true],['text'=>'Carotte','correct'=>false],['text'=>'Pomme de terre seule','correct'=>false],['text'=>'Betterave','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Les repas ivoiriens utilisent souvent le piment comme condiment.",'explanation'=>"Le piment accompagne fréquemment les plats ivoiriens selon les goûts.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel plat à base de pâte de manioc fermentée est souvent servi avec une sauce ?",'explanation'=>"Le placali est une pâte de manioc fermentée consommée avec des sauces.",'options'=>[['text'=>'Placali','correct'=>true],['text'=>'Garba','correct'=>false],['text'=>'Alloco','correct'=>false],['text'=>'Pain brochette','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel nom désigne une grande galette de manioc proche de l’attiéké ?",'explanation'=>"L’attoukpou est une préparation de manioc connue dans le sud ivoirien.",'options'=>[['text'=>'Attoukpou','correct'=>true],['text'=>'Klaklo','correct'=>false],['text'=>'Kédjénou','correct'=>false],['text'=>'Gnangnan','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Le kédjénou est traditionnellement préparé sans ajout important d’eau.",'explanation'=>"La cuisson à l’étouffée permet aux ingrédients de cuire dans leur propre jus.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Culture & Arts'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel instrument de percussion est courant dans plusieurs cultures ivoiriennes ?",'explanation'=>"Le tam-tam accompagne de nombreuses cérémonies et danses.",'options'=>[['text'=>'Tam-tam','correct'=>true],['text'=>'Harpe celtique','correct'=>false],['text'=>'Cornemuse','correct'=>false],['text'=>'Clavecin','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel art est souvent utilisé dans les danses traditionnelles ivoiriennes ?",'explanation'=>"Les masques jouent un rôle important dans plusieurs traditions artistiques.",'options'=>[['text'=>'Masques','correct'=>true],['text'=>'Graffitis numériques','correct'=>false],['text'=>'Origami japonais','correct'=>false],['text'=>'Vitrail gothique','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"La Côte d'Ivoire possède une grande diversité de danses traditionnelles.",'explanation'=>"Chaque région du pays possède des danses et expressions culturelles variées.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel peuple est connu pour les masques appelés Zaouli ?",'explanation'=>"Le Zaouli est associé au peuple Gouro.",'options'=>[['text'=>'Gouro','correct'=>true],['text'=>'Ébrié','correct'=>false],['text'=>'Sénoufo','correct'=>false],['text'=>'Baoulé','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle fête met souvent en valeur les danses, chants et tenues traditionnelles ?",'explanation'=>"Les fêtes traditionnelles valorisent le patrimoine culturel local.",'options'=>[['text'=>'Fête traditionnelle','correct'=>true],['text'=>'Salon automobile','correct'=>false],['text'=>'Défilé militaire étranger','correct'=>false],['text'=>'Tournoi de ski','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel peuple ivoirien est réputé pour certaines sculptures et portes sculptées du nord ?",'explanation'=>"Les Sénoufo sont connus pour plusieurs formes d’art traditionnel.",'options'=>[['text'=>'Sénoufo','correct'=>true],['text'=>'Akan','correct'=>false],['text'=>'Krou','correct'=>false],['text'=>'Ébrié','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville accueille le MASA, marché des arts du spectacle africain ?",'explanation'=>"Le MASA se tient à Abidjan.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Man','correct'=>false],['text'=>'Odienné','correct'=>false],['text'=>'Tabou','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le pagne est un élément important de l’habillement culturel en Côte d'Ivoire.",'explanation'=>"Le pagne est porté lors de nombreuses occasions sociales et culturelles.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel type de conte transmet souvent des valeurs et des leçons dans les familles ivoiriennes ?",'explanation'=>"Les contes traditionnels transmettent des enseignements de génération en génération.",'options'=>[['text'=>'Conte traditionnel','correct'=>true],['text'=>'Bulletin météo','correct'=>false],['text'=>'Code routier','correct'=>false],['text'=>'Catalogue commercial','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel animal est souvent présent dans les contes ou symboles de sagesse en Afrique de l’Ouest ?",'explanation'=>"L’araignée apparaît dans plusieurs récits traditionnels ouest-africains.",'options'=>[['text'=>'Araignée','correct'=>true],['text'=>'Pingouin','correct'=>false],['text'=>'Kangourou','correct'=>false],['text'=>'Panda','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle danse traditionnelle ivoirienne est célèbre pour son masque très expressif ?",'explanation'=>"Le Zaouli est connu pour son masque et ses pas rapides.",'options'=>[['text'=>'Zaouli','correct'=>true],['text'=>'Tango','correct'=>false],['text'=>'Flamenco','correct'=>false],['text'=>'Samba','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Les griots et conteurs ont contribué à la transmission orale en Côte d'Ivoire.",'explanation'=>"La tradition orale occupe une place importante dans la mémoire culturelle.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel domaine artistique le festival Clap Ivoire met-il en valeur ?",'explanation'=>"Clap Ivoire est lié au cinéma et à l’audiovisuel.",'options'=>[['text'=>'Cinéma','correct'=>true],['text'=>'Athlétisme','correct'=>false],['text'=>'Agriculture','correct'=>false],['text'=>'Navigation','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel musée d’Abidjan conserve des objets d’art et de culture ivoiriens ?",'explanation'=>"Le Musée des civilisations de Côte d’Ivoire conserve des collections culturelles.",'options'=>[['text'=>'Musée des civilisations','correct'=>true],['text'=>'Musée du Louvre','correct'=>false],['text'=>'British Museum','correct'=>false],['text'=>'Musée d’Orsay','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Le Zaouli a été inscrit par l’UNESCO au patrimoine culturel immatériel.",'explanation'=>"Cette reconnaissance souligne la valeur culturelle du Zaouli.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Sport ivoirien'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel sport est le plus populaire en Côte d'Ivoire ?",'explanation'=>"Le football est le sport le plus suivi dans le pays.",'options'=>[['text'=>'Football','correct'=>true],['text'=>'Hockey sur glace','correct'=>false],['text'=>'Baseball','correct'=>false],['text'=>'Maracana','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Comment appelle-t-on l’équipe nationale masculine de football ivoirienne ?",'explanation'=>"Les Éléphants est le surnom de l’équipe nationale de football.",'options'=>[['text'=>'Les Éléphants','correct'=>true],['text'=>'Les Lions','correct'=>false],['text'=>'Les Aigles','correct'=>false],['text'=>'Les Panthères','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel ancien footballeur ivoirien est célèbre pour avoir joué à Chelsea ?",'explanation'=>"Didier Drogba est l’un des footballeurs ivoiriens les plus connus.",'options'=>[['text'=>'Didier Drogba','correct'=>true],['text'=>'Samuel Eto’o','correct'=>false],['text'=>'George Weah','correct'=>false],['text'=>'Sadio Mané','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"La Côte d'Ivoire a organisé la CAN 2023.",'explanation'=>"La CAN 2023 s’est déroulée en Côte d’Ivoire en 2024.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle couleur fait partie du maillot courant des équipes nationales ivoiriennes ?",'explanation'=>"L’orange est une couleur emblématique du sport ivoirien.",'options'=>[['text'=>'Orange','correct'=>true],['text'=>'Violet','correct'=>false],['text'=>'Rose','correct'=>false],['text'=>'Noir uniquement','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"En quelle année la Côte d'Ivoire a-t-elle remporté sa première CAN de football ?",'explanation'=>"Le premier titre continental ivoirien date de 1992.",'options'=>[['text'=>'1992','correct'=>true],['text'=>'2006','correct'=>false],['text'=>'2010','correct'=>false],['text'=>'2019','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel gardien ivoirien est célèbre pour son tir au but victorieux à la CAN 1992 ?",'explanation'=>"Alain Gouaméné est associé à la victoire ivoirienne de 1992.",'options'=>[['text'=>'Alain Gouaméné','correct'=>true],['text'=>'Boubacar Barry','correct'=>false],['text'=>'Sylvain Gbohouo','correct'=>false],['text'=>'Badra Ali Sangaré','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel trophée continental la Côte d'Ivoire a remporté en 2015 au football ?",'explanation'=>"Les Éléphants ont remporté la Coupe d’Afrique des nations 2015.",'options'=>[['text'=>'Coupe d’Afrique des nations','correct'=>true],['text'=>'Coupe du monde','correct'=>false],['text'=>'Euro','correct'=>false],['text'=>'Copa América','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Marie-Josée Ta Lou est une sprinteuse ivoirienne.",'explanation'=>"Elle est l’une des grandes figures de l’athlétisme ivoirien.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel athlète ivoirien a remporté l’or olympique en taekwondo en 2016 ?",'explanation'=>"Cheick Cissé a gagné l’or aux Jeux olympiques de Rio en 2016.",'options'=>[['text'=>'Cheick Cissé','correct'=>true],['text'=>'Didier Drogba','correct'=>false],['text'=>'Yaya Touré','correct'=>false],['text'=>'Kolo Touré','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Dans quel sport Ruth Gbagbi a-t-elle remporté des médailles olympiques ?",'explanation'=>"Ruth Gbagbi est une championne ivoirienne de taekwondo.",'options'=>[['text'=>'Taekwondo','correct'=>true],['text'=>'Natation','correct'=>false],['text'=>'Cyclisme','correct'=>false],['text'=>'Tennis','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le stade Alassane Ouattara d’Ebimpé a servi pendant la CAN 2023.",'explanation'=>"Ce stade a accueilli des matchs importants de la compétition.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel club ivoirien a remporté la Ligue des champions africaine en 1998 ?",'explanation'=>"L’ASEC Mimosas a remporté cette compétition continentale en 1998.",'options'=>[['text'=>'ASEC Mimosas','correct'=>true],['text'=>'Africa Sports','correct'=>false],['text'=>'Stella Club','correct'=>false],['text'=>'SOA','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quelle ville ivoirienne a accueilli la finale de la CAN 2023 ?",'explanation'=>"La finale s’est jouée au stade d’Ebimpé dans l’agglomération d’Abidjan.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'San Pedro','correct'=>false],['text'=>'Bouaké','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"La Côte d'Ivoire a remporté la CAN 2023 à domicile.",'explanation'=>"Les Éléphants ont gagné le tournoi organisé en Côte d’Ivoire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Économie & Développement'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel produit agricole est très important pour l’économie ivoirienne ?",'explanation'=>"Le cacao est un produit majeur de l’économie ivoirienne.",'options'=>[['text'=>'Cacao','correct'=>true],['text'=>'Riz polaire','correct'=>false],['text'=>'Olives arctiques','correct'=>false],['text'=>'Houblon alpin','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville abrite un grand port économique en Côte d'Ivoire ?",'explanation'=>"Abidjan est un centre économique majeur avec un port important.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Tengréla','correct'=>false],['text'=>'Séguéla','correct'=>false],['text'=>'Bouna','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"Le cacao est cultivé en Côte d'Ivoire.",'explanation'=>"La Côte d’Ivoire est connue pour sa production de cacao.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel autre produit agricole d’exportation est important en Côte d'Ivoire ?",'explanation'=>"Le café fait partie des cultures d’exportation ivoiriennes.",'options'=>[['text'=>'Café','correct'=>true],['text'=>'Canneberge boréale','correct'=>false],['text'=>'Seigle glacé','correct'=>false],['text'=>'Lavande alpine','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle monnaie est utilisée en Côte d'Ivoire ?",'explanation'=>"La Côte d’Ivoire utilise le franc CFA de l’UEMOA.",'options'=>[['text'=>'Franc CFA','correct'=>true],['text'=>'Naira','correct'=>false],['text'=>'Cedi','correct'=>false],['text'=>'Dollar ivoirien','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel port ivoirien est particulièrement important pour le sud-ouest du pays ?",'explanation'=>"Le port de San Pedro soutient l’activité économique du sud-ouest.",'options'=>[['text'=>'San Pedro','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'Bouaflé','correct'=>false],['text'=>'Odienné','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle organisation économique ouest-africaine utilise le franc CFA en Côte d'Ivoire ?",'explanation'=>"La Côte d’Ivoire appartient à l’UEMOA.",'options'=>[['text'=>'UEMOA','correct'=>true],['text'=>'Union européenne','correct'=>false],['text'=>'Mercosur','correct'=>false],['text'=>'ASEAN','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"L’anacarde est une filière agricole importante en Côte d'Ivoire.",'explanation'=>"La noix de cajou occupe une place importante dans l’agriculture ivoirienne.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel secteur est lié aux plages, parcs et sites historiques ivoiriens ?",'explanation'=>"Le tourisme valorise les paysages, les parcs et le patrimoine.",'options'=>[['text'=>'Tourisme','correct'=>true],['text'=>'Astronomie spatiale','correct'=>false],['text'=>'Pêche polaire','correct'=>false],['text'=>'Ski nordique','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel axe de transport relie Abidjan au Burkina Faso par chemin de fer ?",'explanation'=>"La ligne Abidjan-Ouagadougou relie la Côte d’Ivoire au Burkina Faso.",'options'=>[['text'=>'Abidjan-Ouagadougou','correct'=>true],['text'=>'Abidjan-Dakar par mer','correct'=>false],['text'=>'Yamoussoukro-Lomé','correct'=>false],['text'=>'Man-Bamako direct','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle activité industrielle transforme souvent le cacao ?",'explanation'=>"La transformation du cacao produit notamment beurre, poudre et chocolat.",'options'=>[['text'=>'Transformation agroalimentaire','correct'=>true],['text'=>'Construction navale polaire','correct'=>false],['text'=>'Fabrication de neige','correct'=>false],['text'=>'Extraction de sel lunaire','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le pont Henri-Konan-Bédié facilite les déplacements à Abidjan.",'explanation'=>"Ce pont relie des quartiers importants de l’agglomération abidjanaise.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel produit place souvent la Côte d'Ivoire parmi les principaux producteurs mondiaux ?",'explanation'=>"La Côte d’Ivoire est régulièrement citée parmi les leaders mondiaux du cacao.",'options'=>[['text'=>'Cacao','correct'=>true],['text'=>'Blé','correct'=>false],['text'=>'Pétrole de schiste','correct'=>false],['text'=>'Uranium','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel grand pont d’Abidjan porte le nom d’un ancien président ivoirien ?",'explanation'=>"Le pont Henri-Konan-Bédié porte le nom d’un ancien président ivoirien.",'options'=>[['text'=>'Pont Henri-Konan-Bédié','correct'=>true],['text'=>'Pont Charles-de-Gaulle','correct'=>false],['text'=>'Pont de Brooklyn','correct'=>false],['text'=>'Pont du Gard','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Le port autonome d’Abidjan joue un rôle régional dans les échanges commerciaux.",'explanation'=>"Il sert aussi de plateforme pour des échanges avec des pays voisins enclavés.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Langues & Peuples'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle est la langue officielle de la Côte d'Ivoire ?",'explanation'=>"Le français est la langue officielle de l’État ivoirien.",'options'=>[['text'=>'Français','correct'=>true],['text'=>'Anglais','correct'=>false],['text'=>'Espagnol','correct'=>false],['text'=>'Portugais','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel peuple est très présent dans le centre de la Côte d'Ivoire ?",'explanation'=>"Les Baoulé sont largement associés au centre du pays.",'options'=>[['text'=>'Baoulé','correct'=>true],['text'=>'Inuit','correct'=>false],['text'=>'Basque','correct'=>false],['text'=>'Maori','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"La Côte d'Ivoire compte plusieurs langues nationales.",'explanation'=>"Le pays possède une grande diversité linguistique.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel peuple est associé à la région de Korhogo ?",'explanation'=>"Les Sénoufo sont fortement présents dans le nord, notamment autour de Korhogo.",'options'=>[['text'=>'Sénoufo','correct'=>true],['text'=>'Ébrié','correct'=>false],['text'=>'Abbey','correct'=>false],['text'=>'Dida','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel peuple lagunaire est associé à Abidjan ?",'explanation'=>"Les Ébrié sont un peuple lagunaire lié à la région d’Abidjan.",'options'=>[['text'=>'Ébrié','correct'=>true],['text'=>'Lobi','correct'=>false],['text'=>'Sénoufo','correct'=>false],['text'=>'Koulango','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle grande famille culturelle comprend les Baoulé et les Agni ?",'explanation'=>"Les Baoulé et les Agni appartiennent au grand ensemble Akan.",'options'=>[['text'=>'Akan','correct'=>true],['text'=>'Krou','correct'=>false],['text'=>'Mandé','correct'=>false],['text'=>'Gur','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel peuple est associé à l’ouest forestier ivoirien ?",'explanation'=>"Les Dan font partie des peuples de l’ouest ivoirien.",'options'=>[['text'=>'Dan','correct'=>true],['text'=>'Ébrié','correct'=>false],['text'=>'Baoulé','correct'=>false],['text'=>'Agni','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le dioula sert souvent de langue de communication dans le commerce.",'explanation'=>"Le dioula est largement utilisé comme langue véhiculaire en Côte d’Ivoire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel groupe est souvent rattaché à la grande famille Mandé en Côte d'Ivoire ?",'explanation'=>"Les Malinké sont généralement rattachés au groupe Mandé.",'options'=>[['text'=>'Malinké','correct'=>true],['text'=>'Ébrié','correct'=>false],['text'=>'Baoulé','correct'=>false],['text'=>'Agni','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel peuple est associé à la région de Bondoukou et du nord-est ?",'explanation'=>"Les Koulango sont présents dans le nord-est ivoirien.",'options'=>[['text'=>'Koulango','correct'=>true],['text'=>'Gouro','correct'=>false],['text'=>'Abbey','correct'=>false],['text'=>'Dida','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle langue est associée au peuple Baoulé ?",'explanation'=>"Le baoulé est une langue akan parlée en Côte d’Ivoire.",'options'=>[['text'=>'Baoulé','correct'=>true],['text'=>'Wolof','correct'=>false],['text'=>'Lingala','correct'=>false],['text'=>'Swahili','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Les peuples ivoiriens ont des traditions orales variées.",'explanation'=>"Les récits, proverbes et chants varient selon les communautés.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel ensemble ethnolinguistique est généralement associé aux Bété et aux Dida ?",'explanation'=>"Les Bété et les Dida sont souvent classés dans l’ensemble Krou.",'options'=>[['text'=>'Krou','correct'=>true],['text'=>'Akan','correct'=>false],['text'=>'Gur','correct'=>false],['text'=>'Nilotique','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel peuple est connu pour le masque Zaouli et se rattache au centre-ouest ?",'explanation'=>"Le Zaouli est associé aux Gouro du centre-ouest ivoirien.",'options'=>[['text'=>'Gouro','correct'=>true],['text'=>'Ébrié','correct'=>false],['text'=>'Koulango','correct'=>false],['text'=>'Lobi','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Le nouchi est un parler urbain populaire né en Côte d'Ivoire.",'explanation'=>"Le nouchi est très présent dans la culture urbaine ivoirienne.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Personnalités ivoiriennes'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Qui est Félix Houphouët-Boigny ?",'explanation'=>"Il est le premier président de la Côte d’Ivoire indépendante.",'options'=>[['text'=>'Premier président ivoirien','correct'=>true],['text'=>'Premier astronaute ivoirien','correct'=>false],['text'=>'Inventeur du cacao','correct'=>false],['text'=>'Capitaine des Éléphants en 2023','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel footballeur ivoirien est surnommé Drogba ?",'explanation'=>"Didier Drogba est une grande figure du football ivoirien.",'options'=>[['text'=>'Didier Drogba','correct'=>true],['text'=>'Kolo Touré','correct'=>false],['text'=>'Yaya Touré','correct'=>false],['text'=>'Gervinho','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle sprinteuse ivoirienne est connue sur 100 m et 200 m ?",'explanation'=>"Marie-Josée Ta Lou est une athlète ivoirienne de haut niveau.",'options'=>[['text'=>'Marie-Josée Ta Lou','correct'=>true],['text'=>'Ruth Gbagbi','correct'=>false],['text'=>'Murielle Ahouré','correct'=>false],['text'=>'Josey','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"Yaya Touré est un ancien footballeur international ivoirien.",'explanation'=>"Yaya Touré a joué pour l’équipe nationale ivoirienne.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel artiste ivoirien est associé au coupé-décalé ?",'explanation'=>"Douk Saga est l’une des figures marquantes du coupé-décalé.",'options'=>[['text'=>'Douk Saga','correct'=>true],['text'=>'Alpha Blondy','correct'=>false],['text'=>'Tiken Jah Fakoly','correct'=>false],['text'=>'Aïcha Koné','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel écrivain ivoirien a écrit Les Soleils des indépendances ?",'explanation'=>"Ahmadou Kourouma est l’auteur de ce roman majeur.",'options'=>[['text'=>'Ahmadou Kourouma','correct'=>true],['text'=>'Bernard Dadié','correct'=>false],['text'=>'Véronique Tadjo','correct'=>false],['text'=>'Jean-Marie Adiaffi','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle personnalité ivoirienne est connue pour le reggae engagé ?",'explanation'=>"Tiken Jah Fakoly est connu pour ses chansons reggae engagées.",'options'=>[['text'=>'Tiken Jah Fakoly','correct'=>true],['text'=>'Meiway','correct'=>false],['text'=>'Magic System','correct'=>false],['text'=>'Ariel Sheney','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Bernard Dadié est une figure importante de la littérature ivoirienne.",'explanation'=>"Bernard Dadié a marqué la littérature et la culture ivoiriennes.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle artiste ivoirienne est connue comme chanteuse à la voix puissante ?",'explanation'=>"Aïcha Koné est une chanteuse ivoirienne reconnue.",'options'=>[['text'=>'Aïcha Koné','correct'=>true],['text'=>'Miriam Makeba','correct'=>false],['text'=>'Angélique Kidjo','correct'=>false],['text'=>'Charlotte Dipanda','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel footballeur ivoirien a été capitaine lors de la victoire à la CAN 2015 ?",'explanation'=>"Yaya Touré était une figure majeure de l’équipe ivoirienne en 2015.",'options'=>[['text'=>'Yaya Touré','correct'=>true],['text'=>'Didier Zokora','correct'=>false],['text'=>'Salomon Kalou','correct'=>false],['text'=>'Gervinho','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle taekwondoïste ivoirienne a remporté une médaille olympique ?",'explanation'=>"Ruth Gbagbi a obtenu des médailles olympiques en taekwondo.",'options'=>[['text'=>'Ruth Gbagbi','correct'=>true],['text'=>'Marie-Josée Ta Lou','correct'=>false],['text'=>'Aïcha Koné','correct'=>false],['text'=>'Véronique Tadjo','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Alpha Blondy est un artiste reggae ivoirien.",'explanation'=>"Alpha Blondy est l’une des figures africaines du reggae.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quelle écrivaine ivoirienne a aussi travaillé dans la littérature jeunesse et les arts visuels ?",'explanation'=>"Véronique Tadjo est connue comme écrivaine, poète et artiste.",'options'=>[['text'=>'Véronique Tadjo','correct'=>true],['text'=>'Aïcha Koné','correct'=>false],['text'=>'Ruth Gbagbi','correct'=>false],['text'=>'Josey','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel écrivain ivoirien est aussi connu pour La Carte d’identité ?",'explanation'=>"Jean-Marie Adiaffi est l’auteur de La Carte d’identité.",'options'=>[['text'=>'Jean-Marie Adiaffi','correct'=>true],['text'=>'Ahmadou Kourouma','correct'=>false],['text'=>'Bernard Dadié','correct'=>false],['text'=>'Camara Laye','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Cheick Cissé a donné à la Côte d'Ivoire une médaille d’or olympique.",'explanation'=>"Il a remporté l’or en taekwondo aux Jeux olympiques de 2016.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Musique ivoirienne'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel style musical est né en Côte d'Ivoire au début des années 2000 ?",'explanation'=>"Le coupé-décalé est un mouvement musical ivoirien devenu populaire.",'options'=>[['text'=>'Coupé-décalé','correct'=>true],['text'=>'Flamenco','correct'=>false],['text'=>'Country','correct'=>false],['text'=>'K-pop','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel groupe ivoirien est connu pour la chanson Premier Gaou ?",'explanation'=>"Magic System a popularisé Premier Gaou.",'options'=>[['text'=>'Magic System','correct'=>true],['text'=>'Les Patrons','correct'=>false],['text'=>'Espoir 2000','correct'=>false],['text'=>'Kiff No Beat','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"Alpha Blondy est associé au reggae.",'explanation'=>"Alpha Blondy est une grande figure du reggae africain.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel artiste est souvent lié à la naissance du coupé-décalé ?",'explanation'=>"Douk Saga est considéré comme une figure importante du coupé-décalé.",'options'=>[['text'=>'Douk Saga','correct'=>true],['text'=>'Meiway','correct'=>false],['text'=>'Tiken Jah Fakoly','correct'=>false],['text'=>'Aïcha Koné','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel style musical ivoirien utilise souvent danse, ambiance et expressions populaires ?",'explanation'=>"Le coupé-décalé mêle musique, danse et culture urbaine.",'options'=>[['text'=>'Coupé-décalé','correct'=>true],['text'=>'Opéra baroque','correct'=>false],['text'=>'Jazz manouche','correct'=>false],['text'=>'Musique classique viennoise','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel artiste ivoirien est surnommé le Génie de Kpalèzo ?",'explanation'=>"Meiway est associé au zoblazo et à ce surnom populaire.",'options'=>[['text'=>'Meiway','correct'=>true],['text'=>'Alpha Blondy','correct'=>false],['text'=>'Arafat DJ','correct'=>false],['text'=>'Tiken Jah Fakoly','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel style musical est fortement associé à Meiway ?",'explanation'=>"Meiway a popularisé le zoblazo.",'options'=>[['text'=>'Zoblazo','correct'=>true],['text'=>'Makossa','correct'=>false],['text'=>'Mbalax','correct'=>false],['text'=>'Soukous congolais','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Tiken Jah Fakoly est un chanteur ivoirien de reggae.",'explanation'=>"Il est connu pour son reggae engagé et panafricain.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel artiste du coupé-décalé était aussi appelé DJ Arafat ?",'explanation'=>"Ange Didier Houon était connu sous le nom de DJ Arafat.",'options'=>[['text'=>'Ange Didier Houon','correct'=>true],['text'=>'Didier Drogba','correct'=>false],['text'=>'Alpha Blondy','correct'=>false],['text'=>'Yodé','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel duo ivoirien est connu pour des chansons humoristiques et sociales ?",'explanation'=>"Yodé et Siro sont connus pour leur style zouglou engagé.",'options'=>[['text'=>'Yodé et Siro','correct'=>true],['text'=>'Daft Punk','correct'=>false],['text'=>'P-Square','correct'=>false],['text'=>'Toofan','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel style musical ivoirien est né dans les milieux étudiants d’Abidjan ?",'explanation'=>"Le zouglou est né dans les campus et quartiers d’Abidjan.",'options'=>[['text'=>'Zouglou','correct'=>true],['text'=>'Blues du delta','correct'=>false],['text'=>'Salsa cubaine','correct'=>false],['text'=>'Tango argentin','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le zouglou aborde souvent des thèmes sociaux.",'explanation'=>"Le zouglou raconte fréquemment la vie quotidienne et les questions sociales.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel groupe est associé aux débuts populaires du zouglou avec Gboglo Koffi ?",'explanation'=>"Les Parents du Campus ont marqué les débuts du zouglou.",'options'=>[['text'=>'Les Parents du Campus','correct'=>true],['text'=>'Magic System','correct'=>false],['text'=>'Kiff No Beat','correct'=>false],['text'=>'Espoir 2000','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel groupe ivoirien est souvent associé au rap ivoire moderne ?",'explanation'=>"Kiff No Beat a marqué la scène rap ivoirienne contemporaine.",'options'=>[['text'=>'Kiff No Beat','correct'=>true],['text'=>'Magic System','correct'=>false],['text'=>'Les Patrons','correct'=>false],['text'=>'Wenge Musica','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Le nouchi influence souvent les paroles de musiques urbaines ivoiriennes.",'explanation'=>"Le nouchi nourrit l’expression populaire dans la musique urbaine.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Villes & Régions'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle est la plus grande ville de Côte d'Ivoire ?",'explanation'=>"Abidjan est la plus grande agglomération du pays.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Man','correct'=>false],['text'=>'Daloa','correct'=>false],['text'=>'Odienné','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville est la capitale politique ivoirienne ?",'explanation'=>"Yamoussoukro est la capitale politique de la Côte d’Ivoire.",'options'=>[['text'=>'Yamoussoukro','correct'=>true],['text'=>'Bouaké','correct'=>false],['text'=>'Abidjan','correct'=>false],['text'=>'San Pedro','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville du nord est connue pour la culture sénoufo ?",'explanation'=>"Korhogo est un centre important de la culture sénoufo.",'options'=>[['text'=>'Korhogo','correct'=>true],['text'=>'Aboisso','correct'=>false],['text'=>'Grand-Bassam','correct'=>false],['text'=>'Dabou','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"San Pedro est une ville portuaire ivoirienne.",'explanation'=>"San Pedro possède un port important sur l’Atlantique.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville est connue pour ses montagnes et cascades ?",'explanation'=>"Man est célèbre pour ses paysages montagneux et ses cascades.",'options'=>[['text'=>'Man','correct'=>true],['text'=>'Abobo','correct'=>false],['text'=>'Dabou','correct'=>false],['text'=>'Bingerville','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville est souvent appelée la capitale du centre ivoirien ?",'explanation'=>"Bouaké est une grande ville du centre de la Côte d’Ivoire.",'options'=>[['text'=>'Bouaké','correct'=>true],['text'=>'Tabou','correct'=>false],['text'=>'Boundiali','correct'=>false],['text'=>'Divo','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville historique est classée au patrimoine mondial de l’UNESCO ?",'explanation'=>"Grand-Bassam est reconnue pour son patrimoine historique.",'options'=>[['text'=>'Grand-Bassam','correct'=>true],['text'=>'Séguéla','correct'=>false],['text'=>'Daoukro','correct'=>false],['text'=>'Tengréla','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Daloa est une ville importante du centre-ouest ivoirien.",'explanation'=>"Daloa est un grand pôle urbain du centre-ouest.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville est située près de la frontière avec le Ghana ?",'explanation'=>"Aboisso se trouve dans le sud-est proche du Ghana.",'options'=>[['text'=>'Aboisso','correct'=>true],['text'=>'Odienné','correct'=>false],['text'=>'Man','correct'=>false],['text'=>'Touba','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville est associée au district du Poro ?",'explanation'=>"Korhogo est la principale ville du district du Poro.",'options'=>[['text'=>'Korhogo','correct'=>true],['text'=>'Daloa','correct'=>false],['text'=>'San Pedro','correct'=>false],['text'=>'Agnibilékrou','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville est située dans le nord-ouest ivoirien ?",'explanation'=>"Odienné est une ville importante du nord-ouest.",'options'=>[['text'=>'Odienné','correct'=>true],['text'=>'Grand-Lahou','correct'=>false],['text'=>'Adiaké','correct'=>false],['text'=>'Tiassalé','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Abidjan comprend des communes comme Cocody, Yopougon et Treichville.",'explanation'=>"Ces communes font partie du district autonome d’Abidjan.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quelle ville est historiquement liée au royaume du Sanwi ?",'explanation'=>"Aboisso est associée à l’histoire du royaume du Sanwi.",'options'=>[['text'=>'Aboisso','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'Toumodi','correct'=>false],['text'=>'Danané','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quelle ville est la principale localité du district autonome des Montagnes ?",'explanation'=>"Man est la ville principale du district des Montagnes.",'options'=>[['text'=>'Man','correct'=>true],['text'=>'Bouna','correct'=>false],['text'=>'Abengourou','correct'=>false],['text'=>'Divo','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Yamoussoukro est aussi un district autonome.",'explanation'=>"Yamoussoukro possède le statut de district autonome.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Patrimoine & Tourisme'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville historique ivoirienne est connue pour ses bâtiments coloniaux ?",'explanation'=>"Grand-Bassam conserve un important patrimoine architectural.",'options'=>[['text'=>'Grand-Bassam','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'Odienné','correct'=>false],['text'=>'Ferkessédougou','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel parc national est célèbre pour sa forêt tropicale ?",'explanation'=>"Le parc national de Taï protège une grande forêt tropicale.",'options'=>[['text'=>'Parc national de Taï','correct'=>true],['text'=>'Parc Kruger','correct'=>false],['text'=>'Yellowstone','correct'=>false],['text'=>'Serengeti','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"La Côte d'Ivoire possède des plages sur l’océan Atlantique.",'explanation'=>"Le littoral ivoirien offre plusieurs plages touristiques.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville est connue pour la basilique Notre-Dame de la Paix ?",'explanation'=>"La basilique Notre-Dame de la Paix se trouve à Yamoussoukro.",'options'=>[['text'=>'Yamoussoukro','correct'=>true],['text'=>'Bouaké','correct'=>false],['text'=>'Man','correct'=>false],['text'=>'San Pedro','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville attire les visiteurs avec ses cascades et montagnes ?",'explanation'=>"Man est une destination touristique de l’ouest ivoirien.",'options'=>[['text'=>'Man','correct'=>true],['text'=>'Dabou','correct'=>false],['text'=>'Bingerville','correct'=>false],['text'=>'Treichville','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel site ivoirien est inscrit au patrimoine mondial pour son quartier historique ?",'explanation'=>"La ville historique de Grand-Bassam est inscrite par l’UNESCO.",'options'=>[['text'=>'Grand-Bassam','correct'=>true],['text'=>'Bouaflé','correct'=>false],['text'=>'Gagnoa','correct'=>false],['text'=>'Dimbokro','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel parc national ivoirien est aussi inscrit au patrimoine mondial de l’UNESCO ?",'explanation'=>"Le parc national de Taï est reconnu pour sa biodiversité.",'options'=>[['text'=>'Parc national de Taï','correct'=>true],['text'=>'Parc du Banco','correct'=>false],['text'=>'Parc de la Mé','correct'=>false],['text'=>'Parc urbain de Cocody','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le parc national du Banco se trouve dans l’agglomération d’Abidjan.",'explanation'=>"Le Banco est un espace forestier protégé situé à Abidjan.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle localité côtière est connue pour l’embouchure du fleuve Bandama ?",'explanation'=>"Grand-Lahou est connue pour son lien avec le Bandama et la lagune.",'options'=>[['text'=>'Grand-Lahou','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'Touba','correct'=>false],['text'=>'Bouna','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel site naturel de l’ouest est souvent visité près de Man ?",'explanation'=>"Les cascades de Man sont une attraction touristique connue.",'options'=>[['text'=>'Cascades de Man','correct'=>true],['text'=>'Dunes de Kong','correct'=>false],['text'=>'Lac Victoria','correct'=>false],['text'=>'Chutes du Niagara','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel parc national est situé au nord-est de la Côte d'Ivoire ?",'explanation'=>"Le parc national de la Comoé se trouve au nord-est.",'options'=>[['text'=>'Parc national de la Comoé','correct'=>true],['text'=>'Parc national de Taï','correct'=>false],['text'=>'Parc du Banco','correct'=>false],['text'=>'Parc de la Marahoué','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le tourisme ivoirien combine patrimoine culturel et sites naturels.",'explanation'=>"Le pays propose des villes historiques, parcs, plages et traditions.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel site ivoirien est reconnu pour ses chimpanzés et sa forêt ancienne ?",'explanation'=>"Le parc national de Taï protège une faune remarquable, dont des chimpanzés.",'options'=>[['text'=>'Parc national de Taï','correct'=>true],['text'=>'Plateau d’Abidjan','correct'=>false],['text'=>'Baie de Cocody','correct'=>false],['text'=>'Lac de Buyo uniquement','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel village près de Man est souvent associé à des ponts de lianes traditionnels ?",'explanation'=>"La région de Man est connue pour des ponts de lianes visités par les touristes.",'options'=>[['text'=>'Lieu proche de Man','correct'=>true],['text'=>'Quartier du Plateau','correct'=>false],['text'=>'Port-Bouët','correct'=>false],['text'=>'Vridi','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"Grand-Bassam fut une capitale coloniale avant de devenir un site patrimonial.",'explanation'=>"Son histoire explique l’importance de son patrimoine architectural.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Éducation & Société'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle langue est utilisée comme langue officielle à l’école ivoirienne ?",'explanation'=>"Le français est la langue officielle d’enseignement en Côte d’Ivoire.",'options'=>[['text'=>'Français','correct'=>true],['text'=>'Anglais','correct'=>false],['text'=>'Espagnol','correct'=>false],['text'=>'Allemand','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel examen marque souvent la fin du collège en Côte d'Ivoire ?",'explanation'=>"Le BEPC est un examen important à la fin du premier cycle secondaire.",'options'=>[['text'=>'BEPC','correct'=>true],['text'=>'Baccalauréat','correct'=>false],['text'=>'Doctorat','correct'=>false],['text'=>'Permis de conduire','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"L’école primaire existe dans le système éducatif ivoirien.",'explanation'=>"Le primaire est un niveau de base du système scolaire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel diplôme termine généralement les études secondaires ?",'explanation'=>"Le baccalauréat ouvre l’accès à l’enseignement supérieur.",'options'=>[['text'=>'Baccalauréat','correct'=>true],['text'=>'CEPE','correct'=>false],['text'=>'BEPC','correct'=>false],['text'=>'Certificat de mariage','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville abrite l’Université Félix Houphouët-Boigny ?",'explanation'=>"Cette université est située à Cocody, dans le district d’Abidjan.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Man','correct'=>false],['text'=>'Aboisso','correct'=>false],['text'=>'Bouna','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel examen est passé à la fin du primaire en Côte d'Ivoire ?",'explanation'=>"Le CEPE sanctionne traditionnellement la fin du cycle primaire.",'options'=>[['text'=>'CEPE','correct'=>true],['text'=>'BEPC','correct'=>false],['text'=>'BTS','correct'=>false],['text'=>'Master','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle université publique porte le nom de Félix Houphouët-Boigny ?",'explanation'=>"L’Université Félix Houphouët-Boigny est située à Cocody.",'options'=>[['text'=>'Université de Cocody','correct'=>true],['text'=>'Université de Harvard','correct'=>false],['text'=>'Université de Tokyo','correct'=>false],['text'=>'Université de Dakar uniquement','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Le nouchi est souvent utilisé par les jeunes dans les villes ivoiriennes.",'explanation'=>"Le nouchi est un parler urbain populaire en Côte d’Ivoire.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel média diffuse des informations au public ivoirien ?",'explanation'=>"La télévision, la radio et la presse participent à l’information du public.",'options'=>[['text'=>'Radio','correct'=>true],['text'=>'Boussole seule','correct'=>false],['text'=>'Calendrier lunaire seul','correct'=>false],['text'=>'Thermomètre','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel espace urbain d’Abidjan est connu comme quartier administratif et d’affaires ?",'explanation'=>"Le Plateau concentre administrations, banques et bureaux.",'options'=>[['text'=>'Le Plateau','correct'=>true],['text'=>'Banco forêt','correct'=>false],['text'=>'Assinie plage','correct'=>false],['text'=>'Montagnes de Man','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel service public concerne directement la santé des populations ?",'explanation'=>"Les hôpitaux et centres de santé assurent les soins.",'options'=>[['text'=>'Hôpital','correct'=>true],['text'=>'Stade uniquement','correct'=>false],['text'=>'Port de pêche uniquement','correct'=>false],['text'=>'Marché de gros uniquement','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Les marchés jouent un rôle social et économique important en Côte d'Ivoire.",'explanation'=>"Les marchés sont des lieux d’échanges, de commerce et de vie sociale.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel institut est connu pour former des enseignants du secondaire en Côte d'Ivoire ?",'explanation'=>"L’École normale supérieure d’Abidjan forme notamment des enseignants.",'options'=>[['text'=>'École normale supérieure','correct'=>true],['text'=>'Académie navale islandaise','correct'=>false],['text'=>'Conservatoire de Vienne','correct'=>false],['text'=>'Institut polaire','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel sigle désigne souvent l’enseignement technique et professionnel ?",'explanation'=>"L’ETFP renvoie à l’enseignement technique et à la formation professionnelle.",'options'=>[['text'=>'ETFP','correct'=>true],['text'=>'FIFA','correct'=>false],['text'=>'NASA','correct'=>false],['text'=>'OPEP','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"L’urbanisation d’Abidjan influence fortement les modes de vie ivoiriens.",'explanation'=>"Abidjan concentre emplois, transports, loisirs et services importants.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Christianisme en Côte d’Ivoire'] => [
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle grande basilique se trouve à Yamoussoukro ?",'explanation'=>"La basilique Notre-Dame de la Paix est située à Yamoussoukro.",'options'=>[['text'=>'Notre-Dame de la Paix','correct'=>true],['text'=>'Saint-Pierre de Rome','correct'=>false],['text'=>'Sacré-Cœur de Paris','correct'=>false],['text'=>'Notre-Dame de Chartres','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle fête chrétienne célèbre la naissance de Jésus ?",'explanation'=>"Noël est célébré par les chrétiens de Côte d’Ivoire comme ailleurs.",'options'=>[['text'=>'Noël','correct'=>true],['text'=>'Tabaski','correct'=>false],['text'=>'Ramadan','correct'=>false],['text'=>'Touba','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>1,'question_text'=>"Il existe des églises chrétiennes en Côte d'Ivoire.",'explanation'=>"Le christianisme est présent dans plusieurs régions du pays.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quel jour beaucoup de chrétiens ivoiriens vont à l’église ?",'explanation'=>"Le dimanche est un jour de culte important pour de nombreux chrétiens.",'options'=>[['text'=>'Dimanche','correct'=>true],['text'=>'Mardi uniquement','correct'=>false],['text'=>'Jeudi uniquement','correct'=>false],['text'=>'Samedi soir seulement','correct'=>false]]],
['type'=>'qcm','difficulty'=>1,'question_text'=>"Quelle ville ivoirienne est associée à la basilique Notre-Dame de la Paix ?",'explanation'=>"Yamoussoukro abrite cette basilique célèbre.",'options'=>[['text'=>'Yamoussoukro','correct'=>true],['text'=>'Korhogo','correct'=>false],['text'=>'San Pedro','correct'=>false],['text'=>'Odienné','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel courant chrétien est représenté par des paroisses et diocèses en Côte d'Ivoire ?",'explanation'=>"L’Église catholique est structurée en diocèses dans le pays.",'options'=>[['text'=>'Catholicisme','correct'=>true],['text'=>'Bouddhisme zen','correct'=>false],['text'=>'Shintoïsme','correct'=>false],['text'=>'Taoïsme','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle fête chrétienne commémore la résurrection de Jésus ?",'explanation'=>"Pâques est une fête chrétienne importante célébrée en Côte d’Ivoire.",'options'=>[['text'=>'Pâques','correct'=>true],['text'=>'Aïd el-Fitr','correct'=>false],['text'=>'Aïd el-Kébir','correct'=>false],['text'=>'Nouvel an chinois','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"La basilique de Yamoussoukro est un site religieux et touristique.",'explanation'=>"Elle attire des fidèles et des visiteurs intéressés par son architecture.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel sacrement chrétien est souvent célébré avec la famille en Côte d'Ivoire ?",'explanation'=>"Le baptême est une cérémonie religieuse et familiale importante.",'options'=>[['text'=>'Baptême','correct'=>true],['text'=>'Permis de conduire','correct'=>false],['text'=>'Passeport','correct'=>false],['text'=>'Inscription électorale','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel type de chant accompagne souvent les cultes chrétiens ivoiriens ?",'explanation'=>"Les chorales animent fréquemment les célébrations chrétiennes.",'options'=>[['text'=>'Chants de chorale','correct'=>true],['text'=>'Annonce météo','correct'=>false],['text'=>'Code de la route chanté','correct'=>false],['text'=>'Cri de marché uniquement','correct'=>false]]],
['type'=>'qcm','difficulty'=>2,'question_text'=>"Quelle ville ivoirienne abrite l’archidiocèse où se trouve la cathédrale Saint-Paul ?",'explanation'=>"La cathédrale Saint-Paul est située à Abidjan.",'options'=>[['text'=>'Abidjan','correct'=>true],['text'=>'Man','correct'=>false],['text'=>'Bouna','correct'=>false],['text'=>'Touba','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>2,'question_text'=>"Des communautés protestantes existent en Côte d'Ivoire.",'explanation'=>"Le protestantisme fait partie du paysage chrétien ivoirien.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel architecte a conçu la cathédrale Saint-Paul d’Abidjan ?",'explanation'=>"La cathédrale Saint-Paul a été conçue par l’architecte Aldo Spirito.",'options'=>[['text'=>'Aldo Spirito','correct'=>true],['text'=>'Gustave Eiffel','correct'=>false],['text'=>'Le Corbusier','correct'=>false],['text'=>'Antoni Gaudí','correct'=>false]]],
['type'=>'qcm','difficulty'=>3,'question_text'=>"Quelle personnalité catholique est liée à la consécration de la basilique de Yamoussoukro en 1990 ?",'explanation'=>"Le pape Jean-Paul II a consacré la basilique Notre-Dame de la Paix.",'options'=>[['text'=>'Jean-Paul II','correct'=>true],['text'=>'Paul VI','correct'=>false],['text'=>'François','correct'=>false],['text'=>'Benoît XV','correct'=>false]]],
['type'=>'vrai_faux','difficulty'=>3,'question_text'=>"La cathédrale Saint-Paul d’Abidjan est située dans la commune du Plateau.",'explanation'=>"Elle se trouve au Plateau, quartier administratif d’Abidjan.",'options'=>[['text'=>'Vrai','correct'=>true],['text'=>'Faux','correct'=>false]]],
],
$categories['Foursquare en Côte d’Ivoire'] => [

['type'=>'qcm','difficulty'=>1,'question_text'=>"En quelle année la mission Foursquare a-t-elle commencé en Côte d’Ivoire ?",'explanation'=>"La mission Foursquare en Côte d’Ivoire a commencé en 1986 avec la rencontre du pasteur Kouassi Philippe et du missionnaire Michel Belobaba.",'options'=>[['text'=>'1986','correct'=>true],['text'=>'1989','correct'=>false],['text'=>'1990','correct'=>false],['text'=>'1996','correct'=>false]]],

['type'=>'qcm','difficulty'=>1,'question_text'=>"Avec quel missionnaire le pasteur Kouassi Philippe a-t-il été en contact au début de la mission Foursquare en Côte d’Ivoire ?",'explanation'=>"Le pasteur Kouassi Philippe a rencontré le missionnaire Michel Belobaba du Canada.",'options'=>[['text'=>'Michel Belobaba','correct'=>true],['text'=>'Gregory Fisher','correct'=>false],['text'=>'Louis Quarcoo','correct'=>false],['text'=>'Dave Mersker','correct'=>false]]],

['type'=>'qcm','difficulty'=>1,'question_text'=>"En quelle année les activités de l’Église Foursquare ont-elles effectivement démarré en Côte d’Ivoire ?",'explanation'=>"Même si le premier contact date de 1986, le démarrage effectif des activités a eu lieu en 1989.",'options'=>[['text'=>'1989','correct'=>true],['text'=>'1986','correct'=>false],['text'=>'1993','correct'=>false],['text'=>'2001','correct'=>false]]],

['type'=>'qcm','difficulty'=>1,'question_text'=>"Où l’œuvre Foursquare a-t-elle commencé en Côte d’Ivoire ?",'explanation'=>"Tout a commencé à Yopougon Kouté, chez le pasteur Kouassi Philippe.",'options'=>[['text'=>'Yopougon Kouté','correct'=>true],['text'=>'Daloa','correct'=>false],['text'=>'San-Pédro','correct'=>false],['text'=>'Abengourou','correct'=>false]]],

['type'=>'qcm','difficulty'=>1,'question_text'=>"Qui fut le premier président de l’Église Foursquare en Côte d’Ivoire ?",'explanation'=>"Le pasteur Kouassi Philippe est devenu le premier président de l’Église Foursquare en Côte d’Ivoire.",'options'=>[['text'=>'Kouassi Philippe','correct'=>true],['text'=>'Kacou Séverin','correct'=>false],['text'=>'Louis Quarcoo','correct'=>false],['text'=>'Kouamé Gnepe Marius','correct'=>false]]],

['type'=>'qcm','difficulty'=>2,'question_text'=>"En quelle année a eu lieu la première convention de l’Église Foursquare en Côte d’Ivoire ?",'explanation'=>"La première convention de l’Église Foursquare en Côte d’Ivoire s’est tenue en 1990.",'options'=>[['text'=>'1990','correct'=>true],['text'=>'1986','correct'=>false],['text'=>'1994','correct'=>false],['text'=>'2003','correct'=>false]]],

['type'=>'qcm','difficulty'=>2,'question_text'=>"Quels missionnaires ont été envoyés depuis Los Angeles en 1989 pour soutenir le démarrage de l’œuvre en Côte d’Ivoire ?",'explanation'=>"Dave Mersker et Many Hernandez ont été envoyés par le bureau international depuis Los Angeles.",'options'=>[['text'=>'Dave Mersker et Many Hernandez','correct'=>true],['text'=>'Michel Belobaba et Gregory Fisher','correct'=>false],['text'=>'Louis Quarcoo et N’dré Clovis','correct'=>false],['text'=>'Kacou Séverin et Yohou Paul','correct'=>false]]],

['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel révérend supervisait la jeune Église Foursquare de Côte d’Ivoire depuis le Ghana ?",'explanation'=>"Le Révérend Gregory Fisher supervisait la jeune Église Foursquare de Côte d’Ivoire depuis le Ghana.",'options'=>[['text'=>'Gregory Fisher','correct'=>true],['text'=>'Dave Mersker','correct'=>false],['text'=>'Michel Belobaba','correct'=>false],['text'=>'Harold McPherson','correct'=>false]]],

['type'=>'qcm','difficulty'=>2,'question_text'=>"Quel missionnaire a été choisi président de l’Église Foursquare Côte d’Ivoire après la destitution de Yohou Paul en 1994 ?",'explanation'=>"Après la destitution de Yohou Paul, le missionnaire Louis Quarcoo a été choisi à sa place.",'options'=>[['text'=>'Louis Quarcoo','correct'=>true],['text'=>'Kouassi Philippe','correct'=>false],['text'=>'Kacou Séverin','correct'=>false],['text'=>'Kouamé Gnepe Marius','correct'=>false]]],

['type'=>'qcm','difficulty'=>2,'question_text'=>"Combien de communautés Foursquare existaient au moment de la restructuration sous Louis Quarcoo ?",'explanation'=>"Le document indique qu’à ce moment-là, Foursquare ne comptait que deux communautés : Yopougon SIDECI et Port-Bouët.",'options'=>[['text'=>'Deux communautés','correct'=>true],['text'=>'Six communautés','correct'=>false],['text'=>'Douze communautés','correct'=>false],['text'=>'Plus de cinquante communautés','correct'=>false]]],

['type'=>'qcm','difficulty'=>3,'question_text'=>"Pourquoi le retour de Kacou Séverin fut-il déterminant pour l’expansion de Foursquare en Côte d’Ivoire ?",'explanation'=>"Son retour a permis à Foursquare de bénéficier d’ouvriers déjà formés et prêts pour les veillées, croisades et implantations d’églises.",'options'=>[['text'=>'Parce qu’il est revenu avec un potentiel d’ouvriers formés','correct'=>true],['text'=>'Parce qu’il a fondé Foursquare au niveau international','correct'=>false],['text'=>'Parce qu’il a supprimé les districts','correct'=>false],['text'=>'Parce qu’il a transféré le siège international à Abidjan','correct'=>false]]],

['type'=>'qcm','difficulty'=>3,'question_text'=>"En quelle année la présidence de l’Église Foursquare Côte d’Ivoire a-t-elle été rétrocédée aux Ivoiriens ?",'explanation'=>"En août 1996, la présidence a été rétrocédée aux Ivoiriens et Kacou Séverin a été porté à la tête de l’Église.",'options'=>[['text'=>'1996','correct'=>true],['text'=>'1989','correct'=>false],['text'=>'1990','correct'=>false],['text'=>'2001','correct'=>false]]],

['type'=>'qcm','difficulty'=>3,'question_text'=>"Qui devient président de l’Église Foursquare Côte d’Ivoire en 1996 ?",'explanation'=>"En 1996, l’évangéliste Kacou Séverin devient président de l’Église Foursquare Côte d’Ivoire.",'options'=>[['text'=>'Kacou Séverin','correct'=>true],['text'=>'Kouassi Philippe','correct'=>false],['text'=>'Yohou Paul','correct'=>false],['text'=>'Gregory Fisher','correct'=>false]]],

['type'=>'qcm','difficulty'=>3,'question_text'=>"Quel pasteur a assuré l’intérim après le décès de Kacou Séverin en 2001 ?",'explanation'=>"Après le décès de Kacou Séverin, le pasteur Kouamé Gnepe Marius, alors secrétaire du Bureau National, a assuré l’intérim.",'options'=>[['text'=>'Kouamé Gnepe Marius','correct'=>true],['text'=>'Kouassi Philippe','correct'=>false],['text'=>'Louis Quarcoo','correct'=>false],['text'=>'Michel Belobaba','correct'=>false]]],

['type'=>'qcm','difficulty'=>3,'question_text'=>"Pourquoi le document précise-t-il que Kacou Séverin n’est pas le fondateur de l’Église Foursquare ?",'explanation'=>"Le document précise cela parce que Kacou Séverin a fortement contribué à la croissance de Foursquare en Côte d’Ivoire, mais l’Église Foursquare est une organisation internationale plus ancienne.",'options'=>[['text'=>'Parce qu’il a contribué à la croissance sans être le fondateur','correct'=>true],['text'=>'Parce qu’il n’a jamais appartenu à Foursquare','correct'=>false],['text'=>'Parce qu’il a fondé une autre Église appelée Foursquare','correct'=>false],['text'=>'Parce qu’il était seulement musicien','correct'=>false]]],

]


         ];

        foreach ($questionsByCategory as $categoryId => $questions) {
            foreach ($questions as $questionData) {
                $question = Question::updateOrCreate(
                    [
                        'category_id' => $categoryId,
                        'question_text' => $questionData['question_text'],
                    ],
                    [
                        'type' => $questionData['type'],
                        'explanation' => $questionData['explanation'],
                        'difficulty' => $questionData['difficulty'],
                        'is_active' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );

                foreach ($questionData['options'] as $optionData) {
                    Option::updateOrCreate(
                        [
                            'question_id' => $question->id,
                            'option_text' => $optionData['text'],
                        ],
                        [
                            'is_correct' => $optionData['correct'],
                            'created_at' => now(),
                            'updated_at' => now(),
                        ]
                    );
                }
            }
        }

        $this->command?->info('✅ Questions ajoutées avec succès pour les 14 catégories !');
    }
}